# 第五章 pandas入门

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
import numpy as np

## 5.1 pandas数据结构介绍

### Series

In [3]:
obj = pd.Series([4, -5 ,4, 6])
obj

0    4
1   -5
2    4
3    6
dtype: int64

In [4]:
obj.values

array([ 4, -5,  4,  6], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d','b','a', 'e'])
obj2

d    4
b    7
a   -5
e    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'e'], dtype='object')

In [8]:
obj2['a']

-5

In [9]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
e    3
dtype: int64

In [10]:
obj2[['a', 'b', 'd']] # 可以选取一组值

a   -5
b    7
d    6
dtype: int64

In [11]:
# numpy函数或类似numpy的运算
obj2[obj2 > 0]

d    6
b    7
e    3
dtype: int64

In [12]:
obj2 * 2

d    12
b    14
a   -10
e     6
dtype: int64

In [13]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
e      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [15]:
'f' in obj2

False

In [16]:
# 通过字典创建
sdata = {'Ohio': 35000, 'Taxes': 71000, 'Oregon': 90000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Taxes     71000
Oregon    90000
dtype: int64

In [17]:
# 传入字典的键改变顺序
states = ['Taxes', 'Oregon', 'Ohio', 'California']
obj4 = pd.Series(sdata, states)
obj4

Taxes         71000.0
Oregon        90000.0
Ohio          35000.0
California        NaN
dtype: float64

In [18]:
obj4.isnull()

Taxes         False
Oregon        False
Ohio          False
California     True
dtype: bool

In [19]:
obj4.notnull()

Taxes          True
Oregon         True
Ohio           True
California    False
dtype: bool

In [20]:
pd.isnull(obj4)

Taxes         False
Oregon        False
Ohio          False
California     True
dtype: bool

In [21]:
pd.notnull(obj4)

Taxes          True
Oregon         True
Ohio           True
California    False
dtype: bool

In [22]:
obj3 + obj4 # 自动对齐数据

California         NaN
Ohio           70000.0
Oregon        180000.0
Taxes         142000.0
dtype: float64

In [23]:
# Series本身和索引的name属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
Taxes         71000.0
Oregon        90000.0
Ohio          35000.0
California        NaN
Name: population, dtype: float64

In [24]:
# 赋值改变索引
obj

0    4
1   -5
2    4
3    6
dtype: int64

In [25]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve   -5
Jeff     4
Ryan     6
dtype: int64

### DataFrame

In [26]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
frame.head() # 前五行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
frame.tail() # 后五行

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
pd.DataFrame(data, columns=['year','state','pop']) # 指定列顺序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
....: index=['one', 'two', 'three', 'four',
....: 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
frame2['state'] # 获取一个Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [32]:
frame2.state # 获取一个Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.loc['three'] # 获取行Series

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [34]:
frame2['debt'] = 16.5 # 赋一组值
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [35]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [36]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [37]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [38]:
del frame2['eastern'] # 删除列
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
# 嵌套字典, 外层键为列索引，内层键为行索引
pop = {
    'Nevada': {
        2001: 2.4,
        2002: 2.9
    },
    'Ohio': {
        2000: 1.5,
        2001: 1.7,
        2002: 3.6
    }
}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [40]:
frame3.T # 转置

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [41]:
# 由Series组成的字典也差不多
pdata = {
    'Ohio': frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:2]
}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [42]:
# 指定行列name
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [43]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [44]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 索引对象

In [45]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
index[1] # index对象不可变

'b'

In [48]:
labels = pd.Index(np.arange(3)) # 传递index对象
obj2 = pd.Series([1.5, -2, 12.3], index = labels)
obj2.index is labels

True

In [49]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [50]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [51]:
'Ohio' in frame3.columns

True

In [52]:
2003 in frame3.index

False

## 5.2 基本功能

### 重新索引

In [53]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [54]:
obj.reindex(['a', 'b', 'c', 'd']) # 重新索引

a    0.0
b    1.0
c    2.0
d    NaN
dtype: float64

In [55]:
obj2 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj2

0      blue
2    purple
4    yellow
dtype: object

In [56]:
obj2.reindex(range(6), method='ffill') # 前向值填充

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [57]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [58]:
frame2 = frame.reindex(['a','b','c','d']) # 重新索引列索引
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [59]:
states = ['Texas', 'Utah' ,'California'] # 重新索引
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 丢弃指定轴上的项

In [60]:
# drop
obj

a    0
b    1
c    2
dtype: int64

In [61]:
obj.drop('c')

a    0
b    1
dtype: int64

In [62]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [63]:
frame.drop(['a', 'd'])

Ohio  Texas  California
c     3      4           5

In [64]:
frame.drop(['Ohio'], axis=1) # 或axis='columns'

Texas  California
a      1           2
c      4           5
d      7           8

In [65]:
obj

a    0
b    1
c    2
dtype: int64

In [66]:
obj.drop('c', inplace=True) # 在原数据上删除

In [67]:
obj

a    0
b    1
dtype: int64

### 索引、选取和过滤

In [68]:
# Series利用标签的索引是包含末尾的
obj = pd.Series(range(4), index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int64

In [69]:
obj[:'c']

a    0
b    1
c    2
dtype: int64

In [70]:
obj[:'c'] =  5
obj

a    5
b    5
c    5
d    3
dtype: int64

In [71]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [73]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

特殊情况

In [74]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [75]:
data[data['two'] > 5]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc和iloc进行选取

In [77]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [78]:
data.loc['Ohio', ['two', 'three']] # 选取行列

two      0
three    0
Name: Ohio, dtype: int32

In [79]:
data.iloc[[1,2], :3] # 用整数进行索引

one  two  three
Colorado    0    5      6
Utah        8    9     10

### 整数索引

In [80]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [81]:
# ser[-1] # 报错

整数索引或产生歧义，非整数则不会

最好使用loc和iloc

In [82]:
ser.iloc[-1]

2.0

### 算术运算和数据对齐

In [83]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [84]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [85]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [86]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [87]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 在算术方法中填充值

In [88]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [89]:
df1.loc[1, 'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  NaN   6.0   7.0
2  8.0  9.0  10.0  11.0

In [90]:
df2 

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [91]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [92]:
df1.add(df2, fill_value=0.)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   6.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### DataFrame和Sereis之间的运算

In [93]:
# 跟numpy数组一样
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [94]:
arr[0]

array([0., 1., 2., 3.])

In [95]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [96]:
# frame默认在行上传播，若要在列上传播
frame = pd.DataFrame(arr)
frame

0    1     2     3
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [97]:
series = frame[0]
series

0    0.0
1    4.0
2    8.0
Name: 0, dtype: float64

In [98]:
frame.sub(series, axis=0) # 或axis='index'

0    1    2    3
0  0.0  1.0  2.0  3.0
1  0.0  1.0  2.0  3.0
2  0.0  1.0  2.0  3.0

### 函数应用和映射

In [99]:
# apply
frame

0    1     2     3
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [100]:
frame.apply(lambda x: x.max() - x.min(), axis = 1)

0    3.0
1    3.0
2    3.0
dtype: float64

In [101]:
# applymap
frame.applymap(lambda x: '%.2f' % x)

0     1      2      3
0  0.00  1.00   2.00   3.00
1  4.00  5.00   6.00   7.00
2  8.00  9.00  10.00  11.00

In [102]:
frame[1].map(lambda x: '%.2f' % x)

0    1.00
1    5.00
2    9.00
Name: 1, dtype: object

### 排序和排名

In [103]:
obj = pd.Series(range(4), index=['a', 'c', 'b', 'e'])
obj

a    0
c    1
b    2
e    3
dtype: int64

In [104]:
obj.sort_index()

a    0
b    2
c    1
e    3
dtype: int64

In [105]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'], 
                     columns=['b', 'a', 'e', 'c'])
frame

b  a  e  c
three  0  1  2  3
one    4  5  6  7

In [106]:
frame.sort_index()

b  a  e  c
one    4  5  6  7
three  0  1  2  3

In [107]:
frame.sort_index(axis=1, ascending=False) # axis=1， 然后降序排列

e  c  b  a
three  2  3  0  1
one    6  7  4  5

In [108]:
obj

a    0
c    1
b    2
e    3
dtype: int64

In [109]:
obj.sort_values() # 按照值排列

a    0
c    1
b    2
e    3
dtype: int64

In [110]:
# 排名
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [111]:
obj.rank() # 平均排名破环平级关系

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [112]:
obj.rank(method='first') # 平级按出现顺序排列

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [113]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

### 带有重复标签的轴索引

In [114]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [115]:
obj.index.is_unique

False

In [116]:
obj['a']

a    0
a    1
dtype: int64

In [117]:
obj['c']

4

## 5.3 汇总和计算描述统计

In [118]:
df = pd.DataFrame([[1.4, np.nan], 
                   [7.1, -4.5],
                   [np.nan, np.nan], 
                   [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [119]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [120]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [121]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [122]:
df.sum(axis=1, skipna=False) # skipna禁用‘NA值自动排除’

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [123]:
df.idxmax() # 最大值的索引

one    b
two    d
dtype: object

In [124]:
df.idxmin()

one    d
two    b
dtype: object

In [125]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [126]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [127]:
obj = pd.Series(['a','b', 'a', 'c'])
obj.describe() # 非数值数据

count     4
unique    3
top       a
freq      2
dtype: object

### 相关系数与协方差

In [129]:
import pandas_datareader.data as web

# all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
# pice = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
# volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

### 唯一值、值计数以及成员资格

In [137]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
unique = obj.unique()
unique

array(['c', 'a', 'd', 'b'], dtype=object)

In [138]:
unique.sort()
unique

array(['a', 'b', 'c', 'd'], dtype=object)

In [139]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [140]:
pd.value_counts(obj, sort=False)

c    3
b    2
a    3
d    1
dtype: int64

In [141]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [143]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [144]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object